services:
  backend:
    image: ghcr.io/doud75/setly-backend:latest
    build: null

  frontend:
    image: ghcr.io/doud75/setly-frontend:latest
    build: null
    environment:
      - ADDRESS_HEADER=X-Forwarded-For
