// Code generated by MockGen. DO NOT EDIT.
// Source: api/repository/info_repository.go
//
// Generated by this command:
//
//	mockgen -source=api/repository/info_repository.go -destination=api/repository/mocks/info_repository.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"
	model "setlist/api/model"

	gomock "go.uber.org/mock/gomock"
)

// MockInfoRepository is a mock of InfoRepository interface.
type MockInfoRepository struct {
	ctrl     *gomock.Controller
	recorder *MockInfoRepositoryMockRecorder
	isgomock struct{}
}

// MockInfoRepositoryMockRecorder is the mock recorder for MockInfoRepository.
type MockInfoRepositoryMockRecorder struct {
	mock *MockInfoRepository
}

// NewMockInfoRepository creates a new mock instance.
func NewMockInfoRepository(ctrl *gomock.Controller) *MockInfoRepository {
	mock := &MockInfoRepository{ctrl: ctrl}
	mock.recorder = &MockInfoRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockInfoRepository) EXPECT() *MockInfoRepositoryMockRecorder {
	return m.recorder
}

// GetBandByID mocks base method.
func (m *MockInfoRepository) GetBandByID(ctx context.Context, id int) (model.Band, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBandByID", ctx, id)
	ret0, _ := ret[0].(model.Band)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBandByID indicates an expected call of GetBandByID.
func (mr *MockInfoRepositoryMockRecorder) GetBandByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBandByID", reflect.TypeOf((*MockInfoRepository)(nil).GetBandByID), ctx, id)
}

// GetUserByID mocks base method.
func (m *MockInfoRepository) GetUserByID(ctx context.Context, id int) (model.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserByID", ctx, id)
	ret0, _ := ret[0].(model.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserByID indicates an expected call of GetUserByID.
func (mr *MockInfoRepositoryMockRecorder) GetUserByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserByID", reflect.TypeOf((*MockInfoRepository)(nil).GetUserByID), ctx, id)
}
