// Code generated by MockGen. DO NOT EDIT.
// Source: api/repository/interlude_repository.go
//
// Generated by this command:
//
//	mockgen -source=api/repository/interlude_repository.go -destination=api/repository/mocks/interlude_repository.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"
	model "setlist/api/model"

	gomock "go.uber.org/mock/gomock"
)

// MockInterludeRepository is a mock of InterludeRepository interface.
type MockInterludeRepository struct {
	ctrl     *gomock.Controller
	recorder *MockInterludeRepositoryMockRecorder
	isgomock struct{}
}

// MockInterludeRepositoryMockRecorder is the mock recorder for MockInterludeRepository.
type MockInterludeRepositoryMockRecorder struct {
	mock *MockInterludeRepository
}

// NewMockInterludeRepository creates a new mock instance.
func NewMockInterludeRepository(ctrl *gomock.Controller) *MockInterludeRepository {
	mock := &MockInterludeRepository{ctrl: ctrl}
	mock.recorder = &MockInterludeRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockInterludeRepository) EXPECT() *MockInterludeRepositoryMockRecorder {
	return m.recorder
}

// CreateInterlude mocks base method.
func (m *MockInterludeRepository) CreateInterlude(ctx context.Context, interlude model.Interlude) (model.Interlude, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateInterlude", ctx, interlude)
	ret0, _ := ret[0].(model.Interlude)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateInterlude indicates an expected call of CreateInterlude.
func (mr *MockInterludeRepositoryMockRecorder) CreateInterlude(ctx, interlude any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateInterlude", reflect.TypeOf((*MockInterludeRepository)(nil).CreateInterlude), ctx, interlude)
}

// GetAllInterludesByBandID mocks base method.
func (m *MockInterludeRepository) GetAllInterludesByBandID(ctx context.Context, bandID int) ([]model.Interlude, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllInterludesByBandID", ctx, bandID)
	ret0, _ := ret[0].([]model.Interlude)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllInterludesByBandID indicates an expected call of GetAllInterludesByBandID.
func (mr *MockInterludeRepositoryMockRecorder) GetAllInterludesByBandID(ctx, bandID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllInterludesByBandID", reflect.TypeOf((*MockInterludeRepository)(nil).GetAllInterludesByBandID), ctx, bandID)
}

// GetInterludeByID mocks base method.
func (m *MockInterludeRepository) GetInterludeByID(ctx context.Context, id, bandID int) (model.Interlude, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetInterludeByID", ctx, id, bandID)
	ret0, _ := ret[0].(model.Interlude)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetInterludeByID indicates an expected call of GetInterludeByID.
func (mr *MockInterludeRepositoryMockRecorder) GetInterludeByID(ctx, id, bandID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetInterludeByID", reflect.TypeOf((*MockInterludeRepository)(nil).GetInterludeByID), ctx, id, bandID)
}

// UpdateInterlude mocks base method.
func (m *MockInterludeRepository) UpdateInterlude(ctx context.Context, interlude model.Interlude) (model.Interlude, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateInterlude", ctx, interlude)
	ret0, _ := ret[0].(model.Interlude)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateInterlude indicates an expected call of UpdateInterlude.
func (mr *MockInterludeRepositoryMockRecorder) UpdateInterlude(ctx, interlude any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateInterlude", reflect.TypeOf((*MockInterludeRepository)(nil).UpdateInterlude), ctx, interlude)
}
