// Code generated by MockGen. DO NOT EDIT.
// Source: api/repository/refresh_token_repository.go
//
// Generated by this command:
//
//	mockgen -source=api/repository/refresh_token_repository.go -destination=api/repository/mocks/refresh_token_repository.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"
	model "setlist/api/model"
	time "time"

	gomock "go.uber.org/mock/gomock"
)

// MockRefreshTokenRepository is a mock of RefreshTokenRepository interface.
type MockRefreshTokenRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRefreshTokenRepositoryMockRecorder
	isgomock struct{}
}

// MockRefreshTokenRepositoryMockRecorder is the mock recorder for MockRefreshTokenRepository.
type MockRefreshTokenRepositoryMockRecorder struct {
	mock *MockRefreshTokenRepository
}

// NewMockRefreshTokenRepository creates a new mock instance.
func NewMockRefreshTokenRepository(ctrl *gomock.Controller) *MockRefreshTokenRepository {
	mock := &MockRefreshTokenRepository{ctrl: ctrl}
	mock.recorder = &MockRefreshTokenRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRefreshTokenRepository) EXPECT() *MockRefreshTokenRepositoryMockRecorder {
	return m.recorder
}

// CleanExpiredTokens mocks base method.
func (m *MockRefreshTokenRepository) CleanExpiredTokens(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CleanExpiredTokens", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// CleanExpiredTokens indicates an expected call of CleanExpiredTokens.
func (mr *MockRefreshTokenRepositoryMockRecorder) CleanExpiredTokens(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CleanExpiredTokens", reflect.TypeOf((*MockRefreshTokenRepository)(nil).CleanExpiredTokens), ctx)
}

// DeleteAllUserTokens mocks base method.
func (m *MockRefreshTokenRepository) DeleteAllUserTokens(ctx context.Context, userID int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteAllUserTokens", ctx, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteAllUserTokens indicates an expected call of DeleteAllUserTokens.
func (mr *MockRefreshTokenRepositoryMockRecorder) DeleteAllUserTokens(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteAllUserTokens", reflect.TypeOf((*MockRefreshTokenRepository)(nil).DeleteAllUserTokens), ctx, userID)
}

// DeleteRefreshToken mocks base method.
func (m *MockRefreshTokenRepository) DeleteRefreshToken(ctx context.Context, tokenHash string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteRefreshToken", ctx, tokenHash)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteRefreshToken indicates an expected call of DeleteRefreshToken.
func (mr *MockRefreshTokenRepositoryMockRecorder) DeleteRefreshToken(ctx, tokenHash any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteRefreshToken", reflect.TypeOf((*MockRefreshTokenRepository)(nil).DeleteRefreshToken), ctx, tokenHash)
}

// FindRefreshToken mocks base method.
func (m *MockRefreshTokenRepository) FindRefreshToken(ctx context.Context, tokenHash string) (int, time.Time, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindRefreshToken", ctx, tokenHash)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(time.Time)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// FindRefreshToken indicates an expected call of FindRefreshToken.
func (mr *MockRefreshTokenRepositoryMockRecorder) FindRefreshToken(ctx, tokenHash any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindRefreshToken", reflect.TypeOf((*MockRefreshTokenRepository)(nil).FindRefreshToken), ctx, tokenHash)
}

// GetAllValidTokens mocks base method.
func (m *MockRefreshTokenRepository) GetAllValidTokens(ctx context.Context) ([]model.RefreshToken, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllValidTokens", ctx)
	ret0, _ := ret[0].([]model.RefreshToken)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllValidTokens indicates an expected call of GetAllValidTokens.
func (mr *MockRefreshTokenRepositoryMockRecorder) GetAllValidTokens(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllValidTokens", reflect.TypeOf((*MockRefreshTokenRepository)(nil).GetAllValidTokens), ctx)
}

// GetUserTokenHashes mocks base method.
func (m *MockRefreshTokenRepository) GetUserTokenHashes(ctx context.Context, userID int) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserTokenHashes", ctx, userID)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserTokenHashes indicates an expected call of GetUserTokenHashes.
func (mr *MockRefreshTokenRepositoryMockRecorder) GetUserTokenHashes(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserTokenHashes", reflect.TypeOf((*MockRefreshTokenRepository)(nil).GetUserTokenHashes), ctx, userID)
}

// ReplaceUserRefreshToken mocks base method.
func (m *MockRefreshTokenRepository) ReplaceUserRefreshToken(ctx context.Context, userID int, tokenHash string, expiresAt time.Time) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReplaceUserRefreshToken", ctx, userID, tokenHash, expiresAt)
	ret0, _ := ret[0].(error)
	return ret0
}

// ReplaceUserRefreshToken indicates an expected call of ReplaceUserRefreshToken.
func (mr *MockRefreshTokenRepositoryMockRecorder) ReplaceUserRefreshToken(ctx, userID, tokenHash, expiresAt any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReplaceUserRefreshToken", reflect.TypeOf((*MockRefreshTokenRepository)(nil).ReplaceUserRefreshToken), ctx, userID, tokenHash, expiresAt)
}

// StoreRefreshToken mocks base method.
func (m *MockRefreshTokenRepository) StoreRefreshToken(ctx context.Context, userID int, tokenHash string, expiresAt time.Time) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StoreRefreshToken", ctx, userID, tokenHash, expiresAt)
	ret0, _ := ret[0].(error)
	return ret0
}

// StoreRefreshToken indicates an expected call of StoreRefreshToken.
func (mr *MockRefreshTokenRepositoryMockRecorder) StoreRefreshToken(ctx, userID, tokenHash, expiresAt any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StoreRefreshToken", reflect.TypeOf((*MockRefreshTokenRepository)(nil).StoreRefreshToken), ctx, userID, tokenHash, expiresAt)
}

// UpdateLastUsed mocks base method.
func (m *MockRefreshTokenRepository) UpdateLastUsed(ctx context.Context, tokenHash string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateLastUsed", ctx, tokenHash)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateLastUsed indicates an expected call of UpdateLastUsed.
func (mr *MockRefreshTokenRepositoryMockRecorder) UpdateLastUsed(ctx, tokenHash any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateLastUsed", reflect.TypeOf((*MockRefreshTokenRepository)(nil).UpdateLastUsed), ctx, tokenHash)
}
