// Code generated by MockGen. DO NOT EDIT.
// Source: api/repository/song_repository.go
//
// Generated by this command:
//
//	mockgen -source=api/repository/song_repository.go -destination=api/repository/mocks/song_repository.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"
	model "setlist/api/model"

	gomock "go.uber.org/mock/gomock"
)

// MockSongRepository is a mock of SongRepository interface.
type MockSongRepository struct {
	ctrl     *gomock.Controller
	recorder *MockSongRepositoryMockRecorder
	isgomock struct{}
}

// MockSongRepositoryMockRecorder is the mock recorder for MockSongRepository.
type MockSongRepositoryMockRecorder struct {
	mock *MockSongRepository
}

// NewMockSongRepository creates a new mock instance.
func NewMockSongRepository(ctrl *gomock.Controller) *MockSongRepository {
	mock := &MockSongRepository{ctrl: ctrl}
	mock.recorder = &MockSongRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSongRepository) EXPECT() *MockSongRepositoryMockRecorder {
	return m.recorder
}

// CreateSong mocks base method.
func (m *MockSongRepository) CreateSong(ctx context.Context, song model.Song) (model.Song, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateSong", ctx, song)
	ret0, _ := ret[0].(model.Song)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateSong indicates an expected call of CreateSong.
func (mr *MockSongRepositoryMockRecorder) CreateSong(ctx, song any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateSong", reflect.TypeOf((*MockSongRepository)(nil).CreateSong), ctx, song)
}

// GetAllSongsByBandID mocks base method.
func (m *MockSongRepository) GetAllSongsByBandID(ctx context.Context, bandID int) ([]model.Song, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllSongsByBandID", ctx, bandID)
	ret0, _ := ret[0].([]model.Song)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllSongsByBandID indicates an expected call of GetAllSongsByBandID.
func (mr *MockSongRepositoryMockRecorder) GetAllSongsByBandID(ctx, bandID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllSongsByBandID", reflect.TypeOf((*MockSongRepository)(nil).GetAllSongsByBandID), ctx, bandID)
}

// GetSongByID mocks base method.
func (m *MockSongRepository) GetSongByID(ctx context.Context, id, bandID int) (model.Song, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSongByID", ctx, id, bandID)
	ret0, _ := ret[0].(model.Song)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSongByID indicates an expected call of GetSongByID.
func (mr *MockSongRepositoryMockRecorder) GetSongByID(ctx, id, bandID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSongByID", reflect.TypeOf((*MockSongRepository)(nil).GetSongByID), ctx, id, bandID)
}

// SoftDeleteSong mocks base method.
func (m *MockSongRepository) SoftDeleteSong(ctx context.Context, id, bandID int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SoftDeleteSong", ctx, id, bandID)
	ret0, _ := ret[0].(error)
	return ret0
}

// SoftDeleteSong indicates an expected call of SoftDeleteSong.
func (mr *MockSongRepositoryMockRecorder) SoftDeleteSong(ctx, id, bandID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SoftDeleteSong", reflect.TypeOf((*MockSongRepository)(nil).SoftDeleteSong), ctx, id, bandID)
}

// UpdateSong mocks base method.
func (m *MockSongRepository) UpdateSong(ctx context.Context, song model.Song) (model.Song, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateSong", ctx, song)
	ret0, _ := ret[0].(model.Song)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateSong indicates an expected call of UpdateSong.
func (mr *MockSongRepositoryMockRecorder) UpdateSong(ctx, song any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateSong", reflect.TypeOf((*MockSongRepository)(nil).UpdateSong), ctx, song)
}
